import { describe, expect, it } from 'vitest';
import { ensureSiteSchemaCompatibility, type SiteSchemaInspector } from './siteSchemaCompatibility.js';

function createInspector(
  dialect: SiteSchemaInspector['dialect'],
  options?: {
    hasSitesTable?: boolean;
    existingTables?: string[];
    existingColumns?: string[];
  },
) {
  const executedSql: string[] = [];
  const hasSitesTable = options?.hasSitesTable ?? true;
  const existingTables = new Set(options?.existingTables ?? []);
  const existingColumns = new Set(options?.existingColumns ?? []);

  const inspector: SiteSchemaInspector = {
    dialect,
    async tableExists(table) {
      if (table === 'sites') return hasSitesTable;
      return existingTables.has(table);
    },
    async columnExists(table, column) {
      return table === 'sites' && existingColumns.has(column);
    },
    async execute(sqlText) {
      executedSql.push(sqlText);
    },
  };

  return { inspector, executedSql };
}

describe('ensureSiteSchemaCompatibility', () => {
  it.each([
    {
      dialect: 'postgres' as const,
      expectedSql: [
        'ALTER TABLE "sites" ADD COLUMN "proxy_url" TEXT',
        'ALTER TABLE "sites" ADD COLUMN "use_system_proxy" BOOLEAN DEFAULT FALSE',
        'UPDATE "sites" SET "use_system_proxy" = FALSE WHERE "use_system_proxy" IS NULL',
        'ALTER TABLE "sites" ADD COLUMN "custom_headers" TEXT',
        'ALTER TABLE "sites" ADD COLUMN "external_checkin_url" TEXT',
        'ALTER TABLE "sites" ADD COLUMN "global_weight" DOUBLE PRECISION DEFAULT 1',
        'UPDATE "sites" SET "global_weight" = 1 WHERE "global_weight" IS NULL OR "global_weight" <= 0',
        'CREATE TABLE IF NOT EXISTS "site_disabled_models" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "site_id" INTEGER NOT NULL REFERENCES "sites"("id") ON DELETE CASCADE, "model_name" TEXT NOT NULL, "created_at" TEXT)',
        'CREATE UNIQUE INDEX IF NOT EXISTS "site_disabled_models_site_model_unique" ON "site_disabled_models" ("site_id", "model_name")',
        'CREATE INDEX IF NOT EXISTS "site_disabled_models_site_id_idx" ON "site_disabled_models" ("site_id")',
      ],
    },
    {
      dialect: 'mysql' as const,
      expectedSql: [
        'ALTER TABLE `sites` ADD COLUMN `proxy_url` TEXT NULL',
        'ALTER TABLE `sites` ADD COLUMN `use_system_proxy` BOOLEAN DEFAULT FALSE',
        'UPDATE `sites` SET `use_system_proxy` = FALSE WHERE `use_system_proxy` IS NULL',
        'ALTER TABLE `sites` ADD COLUMN `custom_headers` TEXT NULL',
        'ALTER TABLE `sites` ADD COLUMN `external_checkin_url` TEXT NULL',
        'ALTER TABLE `sites` ADD COLUMN `global_weight` DOUBLE DEFAULT 1',
        'UPDATE `sites` SET `global_weight` = 1 WHERE `global_weight` IS NULL OR `global_weight` <= 0',
        'CREATE TABLE IF NOT EXISTS `site_disabled_models` (`id` INT AUTO_INCREMENT PRIMARY KEY, `site_id` INT NOT NULL, `model_name` VARCHAR(191) NOT NULL, `created_at` TEXT NULL, CONSTRAINT `site_disabled_models_site_fk` FOREIGN KEY (`site_id`) REFERENCES `sites`(`id`) ON DELETE CASCADE)',
        'CREATE UNIQUE INDEX `site_disabled_models_site_model_unique` ON `site_disabled_models` (`site_id`, `model_name`(191))',
        'CREATE INDEX `site_disabled_models_site_id_idx` ON `site_disabled_models` (`site_id`)',
      ],
    },
  ])('adds missing site proxy columns for $dialect', async ({ dialect, expectedSql }) => {
    const { inspector, executedSql } = createInspector(dialect);

    await ensureSiteSchemaCompatibility(inspector);

    expect(executedSql).toEqual(expectedSql);
  });

  it('skips schema changes when sites table does not exist', async () => {
    const { inspector, executedSql } = createInspector('postgres', { hasSitesTable: false });

    await ensureSiteSchemaCompatibility(inspector);

    expect(executedSql).toEqual([]);
  });

  it('does not recreate site_disabled_models when it already exists', async () => {
    const { inspector, executedSql } = createInspector('mysql', {
      existingTables: ['site_disabled_models'],
    });

    await ensureSiteSchemaCompatibility(inspector);

    expect(executedSql).not.toContain('CREATE TABLE IF NOT EXISTS `site_disabled_models` (`id` INT AUTO_INCREMENT PRIMARY KEY, `site_id` INT NOT NULL, `model_name` VARCHAR(191) NOT NULL, `created_at` TEXT NULL, CONSTRAINT `site_disabled_models_site_fk` FOREIGN KEY (`site_id`) REFERENCES `sites`(`id`) ON DELETE CASCADE)');
  });
});
